matrix:
  include:
    - language: python
      env: BUILD_TYPE=api
      python: 3.6
      before_script:
        - cd api
      script:
        - pip install -r requirements.txt 
        - django manage.py migrate

    - language: node_js
      env: BUILD_TYPE=mobile
      node_js:
        - "6.10"

      before_install:
        - sudo apt-get update -qq
        - npm install -g ionic cordova
        - ionic -v
        - cd mobile

      install:
        - npm install

    - language: node_js
      env: BUILD_TYPE=web
      node_js:
        - "6.10"

      before_install:
        - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        - sudo apt-get update -qq
        - sudo apt-get install -qq google-chrome-stable
        - cd web

      install:
        - npm install

notifications:
  email:
    - vitor.nere@gmail.com