matrix:
  include:
    - language: python
      env: BUILD_TYPE=api
      python: 3.6
      before_script:
        - cd api
        - pip install -r requirements.txt
        - python manage.py migrate
      script:
        - python manage.py test

    - language: node_js
      env: BUILD_TYPE=mobile
      node_js:
        - "6.10"

      before_install:
        - sudo apt-get update -qq
        - npm install -g ionic cordova
        - cd mobile

      install:
        - npm install

    - language: node_js
      env: BUILD_TYPE=web
      node_js:
        - "6.10"

      before_install:
        - sudo apt-get update -qq
        - npm install -g @angular/cli
        - cd web

      install:
        - npm install

notifications:
  email:
    - vitor.nere@gmail.com